modelapi:
  #sqlprinter: true
  prifixfilter:
    - insert into 666
  type2javamapping:
    date: timestamp
    timestamp: timestamp
    datetime: datestr
    varchar2: string
    varchar: string
    char: string
    clob: string
    string: string
    int64: long
    integer: long
    smallint: long
    bigint: long
    float: double
    numeric: double
    number: double
    double: double









